CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`whatsapp` varchar(32) NOT NULL,
	`customerType` varchar(32) DEFAULT '新零售',
	`contactName` varchar(128),
	`telephone` varchar(64),
	`address` text,
	`province` varchar(128),
	`city` varchar(128),
	`cityCode` varchar(32),
	`country` varchar(64),
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`),
	CONSTRAINT `customers_whatsapp_unique` UNIQUE(`whatsapp`)
);
--> statement-breakpoint
CREATE TABLE `order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`orderNumber` varchar(128),
	`orderImageUrl` text,
	`size` varchar(32),
	`domesticTrackingNo` varchar(128),
	`sizeRecommendation` text,
	`contactInfo` text,
	`internationalTrackingNo` varchar(128),
	`shipDate` varchar(128),
	`quantity` int DEFAULT 1,
	`source` varchar(128),
	`itemStatus` varchar(64),
	`amountUsd` decimal(12,2) DEFAULT '0',
	`amountCny` decimal(12,2) DEFAULT '0',
	`sellingPrice` decimal(12,2) DEFAULT '0',
	`productCost` decimal(12,2) DEFAULT '0',
	`productProfit` decimal(12,2) DEFAULT '0',
	`productProfitRate` decimal(8,6) DEFAULT '0',
	`shippingCharged` decimal(12,2) DEFAULT '0',
	`shippingActual` decimal(12,2) DEFAULT '0',
	`shippingProfit` decimal(12,2) DEFAULT '0',
	`shippingProfitRate` decimal(8,6) DEFAULT '0',
	`totalProfit` decimal(12,2) DEFAULT '0',
	`profitRate` decimal(8,6) DEFAULT '0',
	`paymentScreenshotUrl` text,
	`remarks` text,
	`paymentStatus` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `order_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderDate` date,
	`staffName` varchar(64),
	`staffId` int,
	`account` varchar(64),
	`customerWhatsapp` varchar(32) NOT NULL,
	`customerId` int,
	`customerType` varchar(32),
	`orderNumber` varchar(128) NOT NULL,
	`orderStatus` varchar(64) DEFAULT '待处理',
	`paymentStatus` varchar(64) DEFAULT '未付款',
	`remarks` text,
	`totalAmountUsd` decimal(12,2) DEFAULT '0',
	`totalAmountCny` decimal(12,2) DEFAULT '0',
	`totalProfit` decimal(12,2) DEFAULT '0',
	`totalProfitRate` decimal(8,6) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`)
);
