CREATE TABLE `daily_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportDate` date NOT NULL,
	`staffId` int NOT NULL,
	`staffName` varchar(128) NOT NULL,
	`whatsAccount` varchar(64),
	`messageCount` int DEFAULT 0,
	`newCustomerCount` int DEFAULT 0,
	`newIntentCount` int DEFAULT 0,
	`returnVisitCount` int DEFAULT 0,
	`newOrderCount` int DEFAULT 0,
	`oldOrderCount` int DEFAULT 0,
	`onlineOrderCount` int DEFAULT 0,
	`itemCount` int DEFAULT 0,
	`totalRevenue` decimal(12,2) DEFAULT '0',
	`onlineRevenue` decimal(12,2) DEFAULT '0',
	`productSellingPrice` decimal(12,2) DEFAULT '0',
	`shippingCharged` decimal(12,2) DEFAULT '0',
	`estimatedProfit` decimal(12,2) DEFAULT '0',
	`estimatedProfitRate` decimal(8,6) DEFAULT '0',
	`telegramPraiseCount` int DEFAULT 0,
	`referralCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_data_id` PRIMARY KEY(`id`)
);
