CREATE TABLE `reshipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reshipDate` date,
	`staffName` varchar(64),
	`staffId` int,
	`account` varchar(64),
	`customerWhatsapp` varchar(255),
	`orderNumber` varchar(128),
	`orderImageUrl` text,
	`size` varchar(64),
	`domesticTrackingNo` varchar(128),
	`sizeRecommendation` text,
	`contactInfo` text,
	`internationalTrackingNo` varchar(128),
	`originalOrderNo` varchar(128),
	`shipDate` date,
	`quantity` int DEFAULT 1,
	`source` varchar(128),
	`orderStatus` varchar(64) DEFAULT '已报货，待发货',
	`totalProfit` decimal(12,2) DEFAULT '0',
	`reshipReason` text,
	`customerPaidAmount` decimal(12,2) DEFAULT '0',
	`reshipCost` decimal(12,2) DEFAULT '0',
	`actualShipping` decimal(12,2) DEFAULT '0',
	`profitLoss` decimal(12,2) DEFAULT '0',
	`originalOrderId` int,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reshipments_id` PRIMARY KEY(`id`)
);
